version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "cpanato"

  - package-ecosystem: npm
    directory: "/webapp"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "cpanato"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "cpanato"
    open-pull-requests-limit: 10
