project_name: mattermost-plugin-alertmanager

dist: goreleaser

builds:
  - skip: true

before:
  hooks:
  - make dist
  - sh -c "echo $COSIGN_PWD | cosign sign-blob --key cosign.key --output dist/alertmanager-{{ .Version }}.sig dist/alertmanager-{{ .Version }}.tar.gz

checksum:
  extra_files:
    - glob: ./dist/alertmanager-*.tar.gz

release:
  prerelease: allow
  draft: true # allow for manual edits
  github:
    owner: cpanato
    name: mattermost-plugin-alertmanager

  extra_files:
    - glob: ./dist/alertmanager-*.tar.gz
    - glob: ./dist/alertmanager-*.sig
