global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
route:
  receiver: mattermost-alertmananger
  group_by:
  - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - dev
  - instance
templates: []
receivers:
- name: 'mattermost-alertmananger'
  webhook_configs:
  - send_resolved: true
    url: 'https://cpanato-outrider.eu.ngrok.io/plugins/alertmanager/api/webhook?token=FR2kDopHGgydR7Zhtyrxvz-8a6Pjavai'
